title: Anabel Yong
url: "https://anabelyong.github.io/"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

use_tracking: yes  

footer: no
footer_url: "https://github.com/anabelyong"
footer_text: "Page design by Ankit Sultana, for Jekyll based template"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
-  name: "Projects"
   link: "projects"
 - name: "Contact"
   link: "contact"
