title: Anabel Yong
url: "https://anabelyong.github.io/"
baseurl: ""  # If your site is at the root domain, this should be empty. Otherwise, it should be "/repository-name"

markdown: kramdown

# Uncomment and update the following line if you have a tracking ID to use
# tracking_id: YOUR_GOOGLE_ANALYTICS_TRACKING_ID

footer: no
footer_url: "https://github.com/anabelyong"
footer_text: "Page design by Ankit Sultana, for Jekyll based template"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "About"
    link: "/"
  - name: "Projects"
    link: "/project"  # Make sure this link is correct. If projects.md is in the root, this is fine.
  - name: "Previous Research Interests"
    link: "/research"   # Same here, ensure this is the correct link to your contact page.
  - name: "Resume"
    link: "cv.pdf"
    openInNewTab: Yes
