title: Researcher
url: "https://anabel-yong.com"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/anabelyong"
footer_text: "Page design by Ankit Sultana, for Jekyll based template"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Contact"
   link: "contact"
